version: "3.7"

services:
  users-service:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - ./.env

  users-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - users-db:/data/db
    env_file:
      - ./.env

volumes:
  users-db:
