version: "3.7"

services:
  users-service:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - ./.env

  users-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - users-db:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15673:15672"

volumes:
  users-db:
